spring.application.name=VinewoodStreet

spring.datasource.url=jdbc:postgresql://localhost:5432/vinewood_street_db
spring.datasource.username=postgres
spring.datasource.password=mlovatto

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true


# Redis
spring.cache.type=redis
spring.cache.redis.time-to-live=10s

# Token
token_password=${TOKEN_PASSWORD}

# Gemini
GEMINI_API_KEY=${GEMINI_API_KEY}
